### ISSUE TITLE
Release Zip?

### ISSUE THREAD

**Issue by DataGamingYT** [Nadelio/SOTF#1]
Just an idea if I may, how about creating a release zip so all files needed are one click?

**Comment by Nadelio** [comment]
I'm pretty sure you can just download the .zip file? That's what my brother just did on his pc.

**Comment by DataGamingYT** [comment]
I mean a release on GitHub. Unless there is already one and I just can't see it on mobile?

**Comment by Nadelio** [comment]
You cannot see it on mobile I'm assuming, because I have done a release of the 3 .py files, and am able to download all 3 as a .zip. I am on pc.
