### ISSUE TITLE
Maybe mistype? Idk. I don't code.

### ISSUE THREAD

**Issue by Sheriff-Nevarez** [Nadelio/SOTF#19]
**Describe the bug**
Line 264 
        `print(f'Player Health: {player_hp}\nPlayer Damage: {player_dmg}\nPlayer Armor: {armor}\nWeapon Damage: {weapon_dmg}\n Inventory: 
` The f'

**Desktop:**
 - [OS] ChromeOS
 - [Browser] Google Chrome
 - [Version] 116.0.5845.168 (Official Build) (64-bit)

**Additional context**
This shows up 6 other times in the code.

**Comment by Nadelio** [comment]
Please don't correct code when you don't know what is happening in the code. These are called f-strings, they allow for formatting of printed strings (see the {}? those are the formatting).
