### ISSUE TITLE
Searching City Crash

### ISSUE THREAD

**Issue by Sheriff-Nevarez** [Nadelio/SOTF#4]
---
name: Bug report
about: Create a report to help us improve
title: 'Searching City Crash'
labels: 'Crash, City, Search'
assignees: 'Nadeli0'

---

**Describe the bug**
When searching the City the program crashes.

**To Reproduce**
1. Go to 'City'
2. Type in 'yes'
3. Click 'enter'

**Expected behavior**
Program should crash/Close

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version N/A

**Additional context**
[bug_report.md](https://github.com/Nadelio/SOTF/files/12402120/bug_report.md)

**Comment by Nadelio** [comment]
Currently this issue only seems to affect people who have downloaded Python from the Microsoft Store, I'll put a note in README.md to warn people against using MS to download Python.
